# -*- coding: utf-8 -*-
"""Multi-Object detection and recognition using YOLOv3 algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jb7UdhlTQB2HgJaURBBe9XtW5i_eKyZL

#Multi-Object detection and recognition using YOLOv3 algorithm - Computer Vision

**Objective:** To implement Multi-object detection and recognition using pre-trained models such as YOLOv3.



**Pre-trained model algorithm used:** YOLOv3

**Description:** Multiple product image is passed as the input image data to the YOLOv3 algorithm for to detect and recogize the objects with correct labels.

**Libraries used**: imageai, dataime, logging, PIL, Numpy

Reference: https://imageai.readthedocs.io/en/latest/detection/
"""

pip install torch torchvision torchaudio opencv-python numpy

pip install imageai

pip install imageai pillow numpy

import os
from imageai.Detection import ObjectDetection
from datetime import datetime
import logging
from PIL import Image
import numpy as np

"""**Setting up the logging configuration**"""

def setup_logging():
  logging.basicConfig(
      level = logging.INFO,
      format = '%(Asctime)s - %(Levelname)s - %(message)s'
  )

"""**Initializing and configuring the pretrained YOLOv3 detection algorithm**"""

def initialize_detector(model_path):
    try:
      detector = ObjectDetection()
      detector.setModelTypeAsYOLOv3()
      detector.setModelPath(model_path)
      detector.loadModel()
      logging.info("Yes, YOLOv3 model got loaded successfully")
      return detector
    except Exception as e:
      logging.error(f"Error initializing detector: {str(e)}")
      raise

"""**Defined an detect_and_recognize_objects function()**"""

def detect_and_recognize_objects(detector, input_image_path, output_image_path, min_probability=30):
    try:
      logging.info(f"Processing image: {input_image_path}")
      detections, extracted_objects = detector.detectObjectsFromImage(
          input_image = input_image_path,
          output_image_path = output_image_path,
          minimum_percentage_probability = min_probability,
          extract_detected_objects = True
      )

      logging.info(f"Detection and recognition completed. Found {len(detections)} objects")
      return detections, extracted_objects

    except:
      logging.error("Error detecting objects")
      raise

"""**Defined an analyze_results() function**"""

def analyze_results(detections, extracted_objects):
  analysis = {
      'total_objects': len(detections),
      'object_counts': {},
      'confidence_levels':{},
      'spatial_distribution': []
  }

  print("\nNow, you can check the Detection and Recognition Results:")
  print("=" * 60)

  for i, (obj, extracted_path) in enumerate(zip(detections, extracted_objects)):
    name = obj["name"]
    probability = obj["percentage_probability"]
    box_points = obj["box_points"]

    analysis['object_counts'][name] = analysis.get(name, 0) + 1

    if name not in analysis['confidence_levels']:
      analysis['confidence_levels'][name] = []
    analysis['confidence_levels'][name].append(probability)

    analysis['spatial_distribution'].append({
        'object':name,
        'location': box_points
    })

    print(f"\nObject #{i+1}:")
    print(f"Recognition class: {name}")
    print(f"Detection Confidence: {probability:.2f}%")
    print(f"Location (x1, y1, x2, y2): {box_points}")
    print(f"Extracted Object Saved: {os.path.basename(extracted_path)}")
    print("=" * 40)

  print("\nAnalysis Summary:")
  print("=" * 60)
  print(f"Total Objects Detected: {analysis['total_objects']}")

  print("\nObject Categories:")
  for obj_name, count in analysis['object_counts'].items():
    avg_confidence = np.mean(analysis['confidence_levels'][obj_name])
    print(f"{obj_name}: {count} instance(s) - Avg. Confidence: {avg_confidence:.2f}%")

  return analysis

"""**Calling the subfunctions from within the main function for displaying detection and recognition results using YoloV3 model**"""

def main():

  setup_logging()
  try:
    execution_path = os.getcwd()
    model_path = os.path.join(execution_path, "yolov3.pt")
    input_image = os.path.join(execution_path, "Household_products.jpg")

    output_dir = os.path.join(execution_path, "detection_results")
    os.makedirs(output_dir, exist_ok = True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_image = os.path.join(output_dir, f"detected_objects_{timestamp}.jpg")

    if not os.path.exists(model_path):
      raise FileNotFoundError("YOLOv3 model file not found. Please download it first.")
    if not os.path.exists(input_image):
      raise FileNotFoundError("Input image file not found")

    detector = initialize_detector(model_path)
    detections, extracted_objects = detect_and_recognize_objects(
      detector = detector,
      input_image_path = input_image,
      output_image_path = output_image,
      min_probability = 30
  )

    analysis = analyze_results(detections, extracted_objects)

    logging.info(f"Processed image saved to: {output_image}")
    logging.info(f"Individual objects extracted: {len(extracted_objects)} files")

  except Exception as e:
    logging.error(f"An error occurred: {str(e)}")
    raise

if __name__ == "__main__":
  main()

"""###The model has detected the multiple objects such as cup and bowl from the image with accuracy greater than over 90%.
  - According the accuracy and confidence score, it has accurately predicted the object detected.
  - Along with object name and detection confidence, it has accurately identified the location of the detected objects.
"""